/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/deployer/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployer/v1/configurations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listConfigurations"];
        put?: never;
        post: operations["createConfiguration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployer/v1/configurations/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validateCredentials"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployer/v1/configurations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConfiguration"];
        put: operations["updateConfiguration"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployer/v1/configurations/{id}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deleteConfiguration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployer/v1/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTargets"];
        put?: never;
        post: operations["createTarget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployer/v1/targets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTarget"];
        put: operations["updateTarget"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployer/v1/targets/{id}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deleteTarget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployer/v1/targets/{id}/configurations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTargetConfigurations"];
        put?: never;
        post: operations["attachConfigurations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployer/v1/targets/{id}/configurations/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["detachConfigurations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployer/v1/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deploy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployer/v1/deploy/target": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deployToTarget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployer/v1/deploy/configurations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deployToConfigurations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployer/v1/deploy/{job_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyDeployment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployer/v1/deploy/{job_id}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rollbackDeployment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployer/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployer/v1/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployer/v1/jobs/{id}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listJobChildren"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployer/v1/jobs/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listJobHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployer/v1/jobs/{id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getJobResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployer/v1/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployer/v1/jobs/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retryJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployer/v1/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployer/v1/statistics/tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTenantStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployer/v1/backup/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["exportBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deployer/v1/backup/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            reason?: string;
            detail?: Record<string, never>;
        };
        Uuid: string;
        Configuration: {
            id: string;
            name: string;
            description: string;
            provider_type: string;
            config: {
                [key: string]: unknown;
            };
            has_credentials: boolean;
            /** @description Required configuration keys left empty for the deployment targets to supply (feature 033, D25); [] when complete. */
            target_supplied?: string[];
            /** @description Names of the stored credential fields (single reads by callers allowed to manage the configuration only). */
            credentials_set?: string[];
            /** @description Values of non-secret credential fields (host, username, access key id); managers only, single reads. Secrets are never returned. */
            credentials_public?: {
                [key: string]: unknown;
            };
            /** @description Stored settings no longer honoured (endpoint, api_base): ignored at deploy time and refused on save. Names only. */
            ignored_config_keys?: string[];
            status: string;
            status_message: string;
            /** Format: date-time */
            last_deployment_at?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ConfigurationPage: {
            items: components["schemas"]["Configuration"][];
            total: number;
            /** @description the page returned (a page beyond the end answers the last page) */
            page: number;
            page_size: number;
            /** @enum {string} */
            sort: "name" | "provider_type" | "status" | "created_at";
            /** @enum {string} */
            order: "asc" | "desc";
        };
        /** @description All set fields must match (AND). Patterns are regular expressions (anchored) or a leading-wildcard glob like *.example.com; unknown fields are refused (400 malformed_body). */
        CertificateFilter: {
            /** @description issuer name (exact) */
            issuer_name?: string;
            /** @description certificate common name pattern */
            common_name_pattern?: string;
            /** @description pattern matched against each SAN */
            san_pattern?: string;
            /** @description subject O (exact) */
            subject_organization?: string;
            /** @description subject OU (exact) */
            subject_org_unit?: string;
            /** @description subject C (exact) */
            subject_country?: string;
        };
        Target: {
            id: string;
            name: string;
            description: string;
            auto_deploy: boolean;
            certificate_filters: components["schemas"]["CertificateFilter"][];
            configuration_ids: string[];
            /** @description Per attached configuration (id -> override); overridable provider config only, never credentials. */
            config_overrides?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** @description Single reads: per attached configuration, labels of required fields the merged configuration lacks (normally empty). */
            missing_required?: {
                [key: string]: string[];
            };
            /** Format: date-time */
            created_at?: string;
        };
        FieldOption: {
            value: string;
            label: string;
        };
        /** @description Field descriptor (contracts/deployer-config-ui.md §2); optional keys are omitted when unset. */
        ProviderField: {
            key: string;
            label: string;
            /**
             * @description absent = string
             * @enum {string}
             */
            type?: "string" | "text" | "url" | "int" | "bool" | "enum" | "string_list" | "key_value" | "host_selector";
            secret: boolean;
            required: boolean;
            /** @description may be supplied or changed by a deployment target override */
            overridable?: boolean;
            /** @description pre-filled on create; type matches type */
            default?: unknown;
            options?: components["schemas"]["FieldOption"][];
            help?: string;
            placeholder?: string;
            /** @enum {string} */
            group?: "connection" | "credentials" | "options";
            min?: number;
            max?: number;
            /** @description string/text/url and each list item; default 1024 */
            max_length?: number;
            /** @description anchored RE2 for string and each string_list item */
            pattern?: string;
            max_items?: number;
        };
        ProviderCapabilities: {
            type: string;
            display_name: string;
            description?: string;
            supports_verify: boolean;
            supports_rollback: boolean;
            /** @description the provider never receives the private key (inventory-agent) */
            delivers_by_reference: boolean;
            /** @description validate contacts the endpoint ("Test connection"); absent = input checks only */
            test_connection?: boolean;
            schema_version?: number;
            config_fields: components["schemas"]["ProviderField"][];
            credential_fields: components["schemas"]["ProviderField"][];
            /** @description groups of config keys of which at least one must be non-empty */
            one_of_required?: string[][];
        };
        ProviderCatalogue: {
            items: components["schemas"]["ProviderCapabilities"][];
        };
        /** @description Unknown top-level fields are refused by the handler (400 malformed_body). */
        ConfigurationInput: {
            name?: string;
            description?: string;
            /** @description create only; an update with another provider is refused (422 provider_type) */
            provider_type?: string;
            config?: {
                [key: string]: unknown;
            };
            /** @description update: empty values keep the stored value; a value replaces only that field */
            credentials?: {
                [key: string]: unknown;
            };
            /** @description update: optional credential fields to remove */
            clear_credentials?: string[];
        };
        /** @description Unknown top-level fields are refused by the handler (400 malformed_body). */
        ValidateRequest: {
            provider_type?: string;
            /** @description merge this configuration's stored credentials (blank secrets on edit) */
            configuration_id?: string;
            config?: {
                [key: string]: unknown;
            };
            credentials?: {
                [key: string]: unknown;
            };
        };
        ValidateResult: {
            valid: boolean;
            /** @enum {string} */
            checked: "probe" | "static" | "partial";
            /** @description target-supplied keys the probe could not use */
            deferred: string[];
            /** @description Previewer providers, e.g. inventory-agent matched_hosts */
            details?: {
                [key: string]: unknown;
            };
        };
        /** @description Unknown top-level fields are refused by the handler (400 malformed_body). */
        AttachRequest: {
            configuration_ids?: string[];
            config_overrides?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** @description alias of config_overrides (contracts/deployer-config-ui.md §4a) */
            overrides?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
        };
        /** @description 422 validation_failed: detail.fields maps config.<key> | credentials.<key> | config_overrides.<key> to a code; values are never echoed. */
        FieldErrors: {
            /** @enum {string} */
            reason?: "validation_failed";
            detail?: {
                fields?: {
                    [key: string]: string;
                };
                /** @description first entry of fields (older clients) */
                field?: string;
                message?: string;
                /** @description attach: the configuration the override errors concern */
                configuration_id?: string;
                /** @description required_by_targets: targets that would become incomplete (<= 20) */
                targets?: {
                    id?: string;
                    name?: string;
                }[];
            };
        };
        TargetPage: {
            items: components["schemas"]["Target"][];
            total: number;
            /** @description the page returned (a page beyond the end answers the last page) */
            page: number;
            page_size: number;
            /** @enum {string} */
            sort: "name" | "created_at";
            /** @enum {string} */
            order: "asc" | "desc";
        };
        Job: {
            id: string;
            /** @enum {string} */
            type: "parent" | "child" | "direct";
            deployment_target_id?: string;
            target_configuration_id?: string;
            parent_job_id?: string;
            certificate_id: string;
            certificate_serial?: string;
            status: string;
            status_message?: string;
            progress: number;
            retry_count: number;
            max_retries: number;
            triggered_by: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            completed_at?: string;
        };
        JobPage: {
            items: components["schemas"]["Job"][];
            total: number;
            /** @description the page returned (a page beyond the end answers the last page) */
            page: number;
            page_size: number;
            /** @enum {string} */
            sort: "created_at" | "status" | "job_type" | "completed_at";
            /** @enum {string} */
            order: "asc" | "desc";
        };
        ChildJobPage: {
            items: components["schemas"]["Job"][];
            total: number;
            page: number;
            page_size: number;
            /** @enum {string} */
            sort: "created_at";
            /** @enum {string} */
            order: "asc" | "desc";
        };
        HistoryEntry: {
            id?: string;
            action: string;
            result: string;
            message?: string;
            duration_ms: number;
            /** Format: date-time */
            created_at: string;
        };
        HistoryPage: {
            items: components["schemas"]["HistoryEntry"][];
            total: number;
            page: number;
            page_size: number;
            /** @enum {string} */
            sort: "created_at";
            /** @enum {string} */
            order: "asc" | "desc";
        };
    };
    responses: never;
    parameters: {
        csrf: string;
        id: string;
        jobId: string;
        page: number;
        pageSize: number;
        /** @description sort direction; defaults to the chosen field's default direction */
        order: "asc" | "desc";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description provider catalogue with field descriptors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderCatalogue"];
                };
            };
        };
    };
    listConfigurations: {
        parameters: {
            query?: {
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["pageSize"];
                /** @description default name (asc) */
                sort?: "name" | "provider_type" | "status" | "created_at";
                /** @description sort direction; defaults to the chosen field's default direction */
                order?: components["parameters"]["order"];
                provider_type?: string;
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description page of configurations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigurationPage"];
                };
            };
            /** @description invalid list parameter (detail.param) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createConfiguration: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ConfigurationInput"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Configuration"];
                };
            };
            /** @description validation_failed (detail.fields) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldErrors"];
                };
            };
        };
    };
    validateCredentials: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResult"];
                };
            };
            /** @description configuration_id unknown in the tenant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description validation_failed (detail.fields) or credentials_rejected (provider refused; no detail) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldErrors"];
                };
            };
        };
    };
    getConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Configuration"];
                };
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateConfiguration: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ConfigurationInput"];
            };
        };
        responses: {
            /** @description updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Configuration"];
                };
            };
            /** @description validation_failed (detail.fields; detail.targets for required_by_targets) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldErrors"];
                };
            };
        };
    };
    deleteConfiguration: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listTargets: {
        parameters: {
            query?: {
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["pageSize"];
                /** @description default name (asc) */
                sort?: "name" | "created_at";
                /** @description sort direction; defaults to the chosen field's default direction */
                order?: components["parameters"]["order"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description page of targets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetPage"];
                };
            };
            /** @description invalid list parameter (detail.param) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createTarget: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description target */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"];
                };
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateTarget: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteTarget: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listTargetConfigurations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    attachConfigurations: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AttachRequest"];
            };
        };
        responses: {
            /** @description attached */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description validation_failed (detail.fields config_overrides.<key>, detail.configuration_id); nothing saved */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldErrors"];
                };
            };
        };
    };
    detachConfigurations: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description detached */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deploy: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description accepted; outcome over SSE */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deployToTarget: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deployToConfigurations: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verifyDeployment: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                job_id: components["parameters"]["jobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description verify result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rollbackDeployment: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                job_id: components["parameters"]["jobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description rollback result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listJobs: {
        parameters: {
            query?: {
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["pageSize"];
                /** @description default created_at (desc) */
                sort?: "created_at" | "status" | "job_type" | "completed_at";
                /** @description sort direction; defaults to the chosen field's default direction */
                order?: components["parameters"]["order"];
                status?: string;
                triggered_by?: string;
                certificate_id?: string;
                job_type?: "parent" | "child" | "direct";
                parent_job_id?: components["schemas"]["Uuid"];
                target_id?: components["schemas"]["Uuid"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description page of jobs (newest first by default) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPage"];
                };
            };
            /** @description invalid list parameter (detail.param) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listJobChildren: {
        parameters: {
            query?: {
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["pageSize"];
                /** @description default created_at (desc) */
                sort?: "created_at";
                /** @description sort direction; defaults to the chosen field's default direction */
                order?: components["parameters"]["order"];
            };
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description page of a parent job's child jobs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChildJobPage"];
                };
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description invalid list parameter (detail.param) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listJobHistory: {
        parameters: {
            query?: {
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["pageSize"];
                /** @description default created_at (desc) */
                sort?: "created_at";
                /** @description sort direction; defaults to the chosen field's default direction */
                order?: components["parameters"]["order"];
            };
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description page of a job's deployment history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryPage"];
                };
            };
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description invalid list parameter (detail.param) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getJobResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description result + history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    retryJob: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description retried */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getStatistics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTenantStatistics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description tenant statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    exportBackup: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description export */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    importBackup: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description imported */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
