// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: deployer/v1/deployer.proto

// deployer.v1 is the service-to-service API of the certificate deployment
// module. It is NOT proxied by the gateway: callers are authenticated platform
// services on the Freya SPIFFE mTLS channel, policed by the module's
// deploy/policy.yaml. The tenant comes from the request and the actor from the
// verified SPIFFE identity. Provider credentials are sealed at rest and never
// returned.

package deployerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TargetConfigurationService_Create_FullMethodName = "/deployer.v1.TargetConfigurationService/Create"
	TargetConfigurationService_Get_FullMethodName    = "/deployer.v1.TargetConfigurationService/Get"
	TargetConfigurationService_List_FullMethodName   = "/deployer.v1.TargetConfigurationService/List"
)

// TargetConfigurationServiceClient is the client API for TargetConfigurationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TargetConfigurationService manages deployment endpoints (provider + config +
// sealed credentials) for other modules.
type TargetConfigurationServiceClient interface {
	Create(ctx context.Context, in *CreateConfigurationRequest, opts ...grpc.CallOption) (*Configuration, error)
	Get(ctx context.Context, in *GetConfigurationRequest, opts ...grpc.CallOption) (*Configuration, error)
	List(ctx context.Context, in *ListConfigurationsRequest, opts ...grpc.CallOption) (*ListConfigurationsResponse, error)
}

type targetConfigurationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTargetConfigurationServiceClient(cc grpc.ClientConnInterface) TargetConfigurationServiceClient {
	return &targetConfigurationServiceClient{cc}
}

func (c *targetConfigurationServiceClient) Create(ctx context.Context, in *CreateConfigurationRequest, opts ...grpc.CallOption) (*Configuration, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Configuration)
	err := c.cc.Invoke(ctx, TargetConfigurationService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetConfigurationServiceClient) Get(ctx context.Context, in *GetConfigurationRequest, opts ...grpc.CallOption) (*Configuration, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Configuration)
	err := c.cc.Invoke(ctx, TargetConfigurationService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetConfigurationServiceClient) List(ctx context.Context, in *ListConfigurationsRequest, opts ...grpc.CallOption) (*ListConfigurationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConfigurationsResponse)
	err := c.cc.Invoke(ctx, TargetConfigurationService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TargetConfigurationServiceServer is the server API for TargetConfigurationService service.
// All implementations must embed UnimplementedTargetConfigurationServiceServer
// for forward compatibility.
//
// TargetConfigurationService manages deployment endpoints (provider + config +
// sealed credentials) for other modules.
type TargetConfigurationServiceServer interface {
	Create(context.Context, *CreateConfigurationRequest) (*Configuration, error)
	Get(context.Context, *GetConfigurationRequest) (*Configuration, error)
	List(context.Context, *ListConfigurationsRequest) (*ListConfigurationsResponse, error)
	mustEmbedUnimplementedTargetConfigurationServiceServer()
}

// UnimplementedTargetConfigurationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTargetConfigurationServiceServer struct{}

func (UnimplementedTargetConfigurationServiceServer) Create(context.Context, *CreateConfigurationRequest) (*Configuration, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedTargetConfigurationServiceServer) Get(context.Context, *GetConfigurationRequest) (*Configuration, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTargetConfigurationServiceServer) List(context.Context, *ListConfigurationsRequest) (*ListConfigurationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedTargetConfigurationServiceServer) mustEmbedUnimplementedTargetConfigurationServiceServer() {
}
func (UnimplementedTargetConfigurationServiceServer) testEmbeddedByValue() {}

// UnsafeTargetConfigurationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TargetConfigurationServiceServer will
// result in compilation errors.
type UnsafeTargetConfigurationServiceServer interface {
	mustEmbedUnimplementedTargetConfigurationServiceServer()
}

func RegisterTargetConfigurationServiceServer(s grpc.ServiceRegistrar, srv TargetConfigurationServiceServer) {
	// If the following call panics, it indicates UnimplementedTargetConfigurationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TargetConfigurationService_ServiceDesc, srv)
}

func _TargetConfigurationService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetConfigurationServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetConfigurationService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetConfigurationServiceServer).Create(ctx, req.(*CreateConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetConfigurationService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetConfigurationServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetConfigurationService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetConfigurationServiceServer).Get(ctx, req.(*GetConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetConfigurationService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConfigurationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetConfigurationServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetConfigurationService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetConfigurationServiceServer).List(ctx, req.(*ListConfigurationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TargetConfigurationService_ServiceDesc is the grpc.ServiceDesc for TargetConfigurationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TargetConfigurationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deployer.v1.TargetConfigurationService",
	HandlerType: (*TargetConfigurationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _TargetConfigurationService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _TargetConfigurationService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _TargetConfigurationService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deployer/v1/deployer.proto",
}

const (
	DeploymentService_Deploy_FullMethodName = "/deployer.v1.DeploymentService/Deploy"
)

// DeploymentServiceClient is the client API for DeploymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DeploymentService lets a module trigger a deployment of an lcm-issued
// certificate to a configuration (a direct job the worker pool runs async).
type DeploymentServiceClient interface {
	Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployResponse, error)
}

type deploymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeploymentServiceClient(cc grpc.ClientConnInterface) DeploymentServiceClient {
	return &deploymentServiceClient{cc}
}

func (c *deploymentServiceClient) Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployResponse)
	err := c.cc.Invoke(ctx, DeploymentService_Deploy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeploymentServiceServer is the server API for DeploymentService service.
// All implementations must embed UnimplementedDeploymentServiceServer
// for forward compatibility.
//
// DeploymentService lets a module trigger a deployment of an lcm-issued
// certificate to a configuration (a direct job the worker pool runs async).
type DeploymentServiceServer interface {
	Deploy(context.Context, *DeployRequest) (*DeployResponse, error)
	mustEmbedUnimplementedDeploymentServiceServer()
}

// UnimplementedDeploymentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeploymentServiceServer struct{}

func (UnimplementedDeploymentServiceServer) Deploy(context.Context, *DeployRequest) (*DeployResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deploy not implemented")
}
func (UnimplementedDeploymentServiceServer) mustEmbedUnimplementedDeploymentServiceServer() {}
func (UnimplementedDeploymentServiceServer) testEmbeddedByValue()                           {}

// UnsafeDeploymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeploymentServiceServer will
// result in compilation errors.
type UnsafeDeploymentServiceServer interface {
	mustEmbedUnimplementedDeploymentServiceServer()
}

func RegisterDeploymentServiceServer(s grpc.ServiceRegistrar, srv DeploymentServiceServer) {
	// If the following call panics, it indicates UnimplementedDeploymentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeploymentService_ServiceDesc, srv)
}

func _DeploymentService_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentServiceServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeploymentService_Deploy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentServiceServer).Deploy(ctx, req.(*DeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeploymentService_ServiceDesc is the grpc.ServiceDesc for DeploymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeploymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deployer.v1.DeploymentService",
	HandlerType: (*DeploymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deploy",
			Handler:    _DeploymentService_Deploy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deployer/v1/deployer.proto",
}
