// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: deployer/v1/deployer.proto

// deployer.v1 is the service-to-service API of the certificate deployment
// module. It is NOT proxied by the gateway: callers are authenticated platform
// services on the Freya SPIFFE mTLS channel, policed by the module's
// deploy/policy.yaml. The tenant comes from the request and the actor from the
// verified SPIFFE identity. Provider credentials are sealed at rest and never
// returned.

package deployerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Configuration struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ProviderType     string                 `protobuf:"bytes,4,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	HasCredentials   bool                   `protobuf:"varint,6,opt,name=has_credentials,json=hasCredentials,proto3" json:"has_credentials,omitempty"` // credentials are never returned
	LastDeploymentAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_deployment_at,json=lastDeploymentAt,proto3" json:"last_deployment_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_deployer_v1_deployer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_deployer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_deployer_v1_deployer_proto_rawDescGZIP(), []int{0}
}

func (x *Configuration) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Configuration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Configuration) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Configuration) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

func (x *Configuration) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Configuration) GetHasCredentials() bool {
	if x != nil {
		return x.HasCredentials
	}
	return false
}

func (x *Configuration) GetLastDeploymentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastDeploymentAt
	}
	return nil
}

type CreateConfigurationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ProviderType    string                 `protobuf:"bytes,4,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"`
	ConfigJson      string                 `protobuf:"bytes,5,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`                // provider config as a JSON object
	CredentialsJson string                 `protobuf:"bytes,6,opt,name=credentials_json,json=credentialsJson,proto3" json:"credentials_json,omitempty"` // sealed at rest; never returned
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateConfigurationRequest) Reset() {
	*x = CreateConfigurationRequest{}
	mi := &file_deployer_v1_deployer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConfigurationRequest) ProtoMessage() {}

func (x *CreateConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_deployer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConfigurationRequest.ProtoReflect.Descriptor instead.
func (*CreateConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_deployer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateConfigurationRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateConfigurationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateConfigurationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateConfigurationRequest) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

func (x *CreateConfigurationRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *CreateConfigurationRequest) GetCredentialsJson() string {
	if x != nil {
		return x.CredentialsJson
	}
	return ""
}

type GetConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigurationRequest) Reset() {
	*x = GetConfigurationRequest{}
	mi := &file_deployer_v1_deployer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigurationRequest) ProtoMessage() {}

func (x *GetConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_deployer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigurationRequest.ProtoReflect.Descriptor instead.
func (*GetConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_deployer_proto_rawDescGZIP(), []int{2}
}

func (x *GetConfigurationRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetConfigurationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListConfigurationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ProviderType  string                 `protobuf:"bytes,2,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"` // optional filter
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                 // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigurationsRequest) Reset() {
	*x = ListConfigurationsRequest{}
	mi := &file_deployer_v1_deployer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigurationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigurationsRequest) ProtoMessage() {}

func (x *ListConfigurationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_deployer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigurationsRequest.ProtoReflect.Descriptor instead.
func (*ListConfigurationsRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_deployer_proto_rawDescGZIP(), []int{3}
}

func (x *ListConfigurationsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListConfigurationsRequest) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

func (x *ListConfigurationsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListConfigurationsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Configurations []*Configuration       `protobuf:"bytes,1,rep,name=configurations,proto3" json:"configurations,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListConfigurationsResponse) Reset() {
	*x = ListConfigurationsResponse{}
	mi := &file_deployer_v1_deployer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigurationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigurationsResponse) ProtoMessage() {}

func (x *ListConfigurationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_deployer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigurationsResponse.ProtoReflect.Descriptor instead.
func (*ListConfigurationsResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_deployer_proto_rawDescGZIP(), []int{4}
}

func (x *ListConfigurationsResponse) GetConfigurations() []*Configuration {
	if x != nil {
		return x.Configurations
	}
	return nil
}

type DeployRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CertificateId   string                 `protobuf:"bytes,2,opt,name=certificate_id,json=certificateId,proto3" json:"certificate_id,omitempty"`
	ConfigurationId string                 `protobuf:"bytes,3,opt,name=configuration_id,json=configurationId,proto3" json:"configuration_id,omitempty"`
	Trigger         string                 `protobuf:"bytes,4,opt,name=trigger,proto3" json:"trigger,omitempty"` // manual | event | auto_renewal (default manual)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	mi := &file_deployer_v1_deployer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_deployer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_deployer_proto_rawDescGZIP(), []int{5}
}

func (x *DeployRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeployRequest) GetCertificateId() string {
	if x != nil {
		return x.CertificateId
	}
	return ""
}

func (x *DeployRequest) GetConfigurationId() string {
	if x != nil {
		return x.ConfigurationId
	}
	return ""
}

func (x *DeployRequest) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

type DeployResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // processing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployResponse) Reset() {
	*x = DeployResponse{}
	mi := &file_deployer_v1_deployer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResponse) ProtoMessage() {}

func (x *DeployResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_deployer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResponse.ProtoReflect.Descriptor instead.
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_deployer_proto_rawDescGZIP(), []int{6}
}

func (x *DeployResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *DeployResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_deployer_v1_deployer_proto protoreflect.FileDescriptor

const file_deployer_v1_deployer_proto_rawDesc = "" +
	"\n" +
	"\x1adeployer/v1/deployer.proto\x12\vdeployer.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x02\n" +
	"\rConfiguration\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rprovider_type\x18\x04 \x01(\tR\fproviderType\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12'\n" +
	"\x0fhas_credentials\x18\x06 \x01(\bR\x0ehasCredentials\x12H\n" +
	"\x12last_deployment_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x10lastDeploymentAt\"\xe0\x01\n" +
	"\x1aCreateConfigurationRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rprovider_type\x18\x04 \x01(\tR\fproviderType\x12\x1f\n" +
	"\vconfig_json\x18\x05 \x01(\tR\n" +
	"configJson\x12)\n" +
	"\x10credentials_json\x18\x06 \x01(\tR\x0fcredentialsJson\"F\n" +
	"\x17GetConfigurationRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"u\n" +
	"\x19ListConfigurationsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12#\n" +
	"\rprovider_type\x18\x02 \x01(\tR\fproviderType\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"`\n" +
	"\x1aListConfigurationsResponse\x12B\n" +
	"\x0econfigurations\x18\x01 \x03(\v2\x1a.deployer.v1.ConfigurationR\x0econfigurations\"\x98\x01\n" +
	"\rDeployRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12%\n" +
	"\x0ecertificate_id\x18\x02 \x01(\tR\rcertificateId\x12)\n" +
	"\x10configuration_id\x18\x03 \x01(\tR\x0fconfigurationId\x12\x18\n" +
	"\atrigger\x18\x04 \x01(\tR\atrigger\"?\n" +
	"\x0eDeployResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\x8d\x02\n" +
	"\x1aTargetConfigurationService\x12M\n" +
	"\x06Create\x12'.deployer.v1.CreateConfigurationRequest\x1a\x1a.deployer.v1.Configuration\x12G\n" +
	"\x03Get\x12$.deployer.v1.GetConfigurationRequest\x1a\x1a.deployer.v1.Configuration\x12W\n" +
	"\x04List\x12&.deployer.v1.ListConfigurationsRequest\x1a'.deployer.v1.ListConfigurationsResponse2V\n" +
	"\x11DeploymentService\x12A\n" +
	"\x06Deploy\x12\x1a.deployer.v1.DeployRequest\x1a\x1b.deployer.v1.DeployResponseBNZLgithub.com/go-freya/freya/services/deployer/api/proto/deployer/v1;deployerv1b\x06proto3"

var (
	file_deployer_v1_deployer_proto_rawDescOnce sync.Once
	file_deployer_v1_deployer_proto_rawDescData []byte
)

func file_deployer_v1_deployer_proto_rawDescGZIP() []byte {
	file_deployer_v1_deployer_proto_rawDescOnce.Do(func() {
		file_deployer_v1_deployer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deployer_v1_deployer_proto_rawDesc), len(file_deployer_v1_deployer_proto_rawDesc)))
	})
	return file_deployer_v1_deployer_proto_rawDescData
}

var file_deployer_v1_deployer_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_deployer_v1_deployer_proto_goTypes = []any{
	(*Configuration)(nil),              // 0: deployer.v1.Configuration
	(*CreateConfigurationRequest)(nil), // 1: deployer.v1.CreateConfigurationRequest
	(*GetConfigurationRequest)(nil),    // 2: deployer.v1.GetConfigurationRequest
	(*ListConfigurationsRequest)(nil),  // 3: deployer.v1.ListConfigurationsRequest
	(*ListConfigurationsResponse)(nil), // 4: deployer.v1.ListConfigurationsResponse
	(*DeployRequest)(nil),              // 5: deployer.v1.DeployRequest
	(*DeployResponse)(nil),             // 6: deployer.v1.DeployResponse
	(*timestamppb.Timestamp)(nil),      // 7: google.protobuf.Timestamp
}
var file_deployer_v1_deployer_proto_depIdxs = []int32{
	7, // 0: deployer.v1.Configuration.last_deployment_at:type_name -> google.protobuf.Timestamp
	0, // 1: deployer.v1.ListConfigurationsResponse.configurations:type_name -> deployer.v1.Configuration
	1, // 2: deployer.v1.TargetConfigurationService.Create:input_type -> deployer.v1.CreateConfigurationRequest
	2, // 3: deployer.v1.TargetConfigurationService.Get:input_type -> deployer.v1.GetConfigurationRequest
	3, // 4: deployer.v1.TargetConfigurationService.List:input_type -> deployer.v1.ListConfigurationsRequest
	5, // 5: deployer.v1.DeploymentService.Deploy:input_type -> deployer.v1.DeployRequest
	0, // 6: deployer.v1.TargetConfigurationService.Create:output_type -> deployer.v1.Configuration
	0, // 7: deployer.v1.TargetConfigurationService.Get:output_type -> deployer.v1.Configuration
	4, // 8: deployer.v1.TargetConfigurationService.List:output_type -> deployer.v1.ListConfigurationsResponse
	6, // 9: deployer.v1.DeploymentService.Deploy:output_type -> deployer.v1.DeployResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_deployer_v1_deployer_proto_init() }
func file_deployer_v1_deployer_proto_init() {
	if File_deployer_v1_deployer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deployer_v1_deployer_proto_rawDesc), len(file_deployer_v1_deployer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_deployer_v1_deployer_proto_goTypes,
		DependencyIndexes: file_deployer_v1_deployer_proto_depIdxs,
		MessageInfos:      file_deployer_v1_deployer_proto_msgTypes,
	}.Build()
	File_deployer_v1_deployer_proto = out.File
	file_deployer_v1_deployer_proto_goTypes = nil
	file_deployer_v1_deployer_proto_depIdxs = nil
}
