// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	gocontext "context"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-tangra/go-tangra-common/viewer"
	"github.com/go-tangra/go-tangra-deployer/internal/cert"
	"github.com/go-tangra/go-tangra-deployer/internal/data"
	"github.com/go-tangra/go-tangra-deployer/internal/event"
	"github.com/go-tangra/go-tangra-deployer/internal/metrics"
	"github.com/go-tangra/go-tangra-deployer/internal/server"
	"github.com/go-tangra/go-tangra-deployer/internal/service"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
)

import (
	_ "github.com/go-tangra/go-tangra-deployer/pkg/deploy/providers"
)

// Injectors from wire.go:

// initApp initializes the Wire provider entry for the kratos application.
//
// Parameters:
//   - *bootstrap.Context: bootstrap context
//
// Returns:
//   - *kratos.App: constructed application instance
//   - func(): cleanup function to run on shutdown
//   - error: possible construction error
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	v, err := cert.NewCertManager(context)
	if err != nil {
		return nil, nil, err
	}
	entClient, cleanup, err := data.NewEntClient(context)
	if err != nil {
		return nil, nil, err
	}
	auditLogRepo := data.NewAuditLogRepo(context, entClient)
	deploymentTargetRepo := data.NewDeploymentTargetRepo(context, entClient)
	targetConfigurationRepo := data.NewTargetConfigurationRepo(context, entClient)
	collector := metrics.NewCollector(context)
	deploymentTargetService := service.NewDeploymentTargetService(context, deploymentTargetRepo, targetConfigurationRepo, collector)
	targetConfigurationService := service.NewTargetConfigurationService(context, targetConfigurationRepo, collector)
	deploymentJobRepo := data.NewDeploymentJobRepo(context, entClient)
	deploymentHistoryRepo := data.NewDeploymentHistoryRepo(context, entClient)
	deploymentJobService := service.NewDeploymentJobService(context, deploymentJobRepo, deploymentTargetRepo, targetConfigurationRepo, deploymentHistoryRepo, collector)
	deploymentService := service.NewDeploymentService(context, deploymentJobRepo, deploymentTargetRepo, targetConfigurationRepo, deploymentHistoryRepo, targetConfigurationService, collector)
	statisticsRepo := data.NewStatisticsRepo(context, entClient)
	statisticsService := service.NewStatisticsService(context, statisticsRepo)
	backupService := service.NewBackupService(context, entClient)
	grpcServer := server.NewGRPCServer(context, v, collector, auditLogRepo, deploymentTargetService, targetConfigurationService, deploymentJobService, deploymentService, statisticsService, backupService)
	httpServer := server.NewHTTPServer(context)
	client, cleanup2, err := data.NewRedisClient(context)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	handler := event.NewHandler(context, deploymentTargetRepo, deploymentJobRepo)
	subscriber := event.NewSubscriber(context, client, handler)
	registrationClient, err := data.NewRegistrationClient(context)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	moduleDialer := data.NewModuleDialer(context, registrationClient)
	lcmClient, cleanup3, err := data.NewLcmClient(context, moduleDialer)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	jobExecutor := service.NewJobExecutor(context, deploymentJobRepo, targetConfigurationRepo, deploymentHistoryRepo, targetConfigurationService, lcmClient, collector)

	// Seed Prometheus metrics from database
	seedCtx := viewer.NewSystemViewerContext(gocontext.Background())
	collector.Seed(seedCtx, statisticsRepo)

	app := newApp(context, grpcServer, httpServer, subscriber, jobExecutor, registrationClient)
	return app, func() {
		collector.Stop(gocontext.Background())
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
